name: spaceman_predictor
description: A simple app to predict Spaceman multipliers manually with a basic AI model.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.64.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true